# Procesamiento y Limpieza de los Datos

Al no haber Missing Values y sólo duplicados se procede a eliminar los mismos dado que su representación es infima sobre los datos representando unicamente un 0.44% (en terminos abstolutos nos deja un total de filas duplicadas de 28.473 sobre un total de registros de 6.489.062).

Resumiendo, únicamente se hará un procesamiento sobre la eliminación de los valores duplicados.

In [13]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('C:/Users/jmorano/Documents/Plantillas personalizadas de Office/Coderhouse/Data Science/Modulo 2 - Data Science Fundamentos para la Ciencia de Datos II/Proyecto - Juan Martin Morano/Data/Raw/full_data_flightdelay.csv', sep=',')

In [6]:
df_sin_duplicados = df.drop_duplicates()

# Mostrar el DataFrame sin duplicados
print("\nDataFrame sin duplicados:")
df_sin_duplicados

DataFrame sin duplicados:

,MONTH,DAY_OF_WEEK,DEP_DEL15,DEP_TIME_BLK,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,CARRIER_NAME,AIRPORT_FLIGHTS_MONTH,...,PLANE_AGE,DEPARTING_AIRPORT,LATITUDE,LONGITUDE,PREVIOUS_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND
0,1,7,0,0800-0859,2,1,25,143,Southwest Airlines Co.,13056,...,8,McCarran International,36.080,-115.152,NONE,0.00,0.0,0.0,65.0,2.91
1,1,7,0,0700-0759,7,1,29,191,Delta Air Lines Inc.,13056,...,3,McCarran International,36.080,-115.152,NONE,0.00,0.0,0.0,65.0,2.91
2,1,7,0,0600-0659,7,1,27,199,Delta Air Lines Inc.,13056,...,18,McCarran International,36.080,-115.152,NONE,0.00,0.0,0.0,65.0,2.91
3,1,7,0,0600-0659,9,1,27,180,Delta Air Lines Inc.,13056,...,2,McCarran International,36.080,-115.152,NONE,0.00,0.0,0.0,65.0,2.91
4,1,7,0,0001-0559,7,1,10,182,Spirit Air Lines,13056,...,1,McCarran International,36.080,-115.152,NONE,0.00,0.0,0.0,65.0,2.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6489057,12,7,0,2300-2359,1,11,3,123,Hawaiian Airlines Inc.,1318,...,18,Lihue Airport,21.979,-159.346,Honolulu International,0.06,0.0,0.0,84.0,15.21
6489058,12,7,0,1800-1859,1,11,2,123,Hawaiian Airlines Inc.,1318,...,16,Lihue Airport,21.979,-159.346,Honolulu International,0.06,0.0,0.0,84.0,15.21
6489059,12,7,0,2000-2059,1,11,2,123,Hawaiian Airlines Inc.,1318,...,18,Lihue Airport,21.979,-159.346,Honolulu International,0.06,0.0,0.0,84.0,15.21
6489060,12,7,0,2100-2159,1,12,3,123,Hawaiian Airlines Inc.,1318,...,18,Lihue Airport,21.979,-159.346,Honolulu International,0.06,0.0,0.0,84.0,15.21
6489061,12,7,1,2100-2159,1,12,3,123,Hawaiian Airlines Inc.,1318,...,15,Lihue Airport,21.979,-159.346,Honolulu International,0.06,0.0,0.0,84.0,15.21

In [18]:
#Control de la eliminación exitosa
if (6489062 - 28473) == df_sin_duplicados.shape[0]:
    print("Eliminación con Éxito")
else: print("Revisar")

Eliminación con Éxito

In [17]:
#Control de las columnas que quedarán en el dataframe procesado
df.columns

Index(['MONTH', 'DAY_OF_WEEK', 'DEP_DEL15', 'DEP_TIME_BLK', 'DISTANCE_GROUP',
       'SEGMENT_NUMBER', 'CONCURRENT_FLIGHTS', 'NUMBER_OF_SEATS',
       'CARRIER_NAME', 'AIRPORT_FLIGHTS_MONTH', 'AIRLINE_FLIGHTS_MONTH',
       'AIRLINE_AIRPORT_FLIGHTS_MONTH', 'AVG_MONTHLY_PASS_AIRPORT',
       'AVG_MONTHLY_PASS_AIRLINE', 'FLT_ATTENDANTS_PER_PASS',
       'GROUND_SERV_PER_PASS', 'PLANE_AGE', 'DEPARTING_AIRPORT', 'LATITUDE',
       'LONGITUDE', 'PREVIOUS_AIRPORT', 'PRCP', 'SNOW', 'SNWD', 'TMAX',
       'AWND'],
      dtype='object')

In [20]:
df_sin_duplicados.to_csv('C:/Users/jmorano/Documents/Plantillas personalizadas de Office/Coderhouse/Data Science/Modulo 2 - Data Science Fundamentos para la Ciencia de Datos II/Proyecto - Juan Martin Morano/Data/Processed/full_data_flightdelay_processed.csv')

A continuación se realizará la creación de una semilla, plantada en 42, para crear una muestra que se mantenga fija en caso de necesitarse para posteriores pruebas. Esta misma será guardada en la carpeta de procesados para contar con su fácil disponibilidad para lo que se necesite.

In [26]:
muestra_df = df.sample(6000,random_state=42)
muestra_df

,MONTH,DAY_OF_WEEK,DEP_DEL15,DEP_TIME_BLK,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,CARRIER_NAME,AIRPORT_FLIGHTS_MONTH,...,PLANE_AGE,DEPARTING_AIRPORT,LATITUDE,LONGITUDE,PREVIOUS_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND
984735,3,5,0,1500-1559,3,4,27,69,"Midwest Airline, Inc.",11965,...,11,Ronald Reagan Washington National,38.852,-77.037,Eppley Airfield,0.00,0.0,0.0,68.0,4.47
4740332,9,7,0,2200-2259,5,1,7,128,American Airlines Inc.,6740,...,6,Miami International,25.792,-80.286,NONE,0.00,0.0,0.0,94.0,5.82
6361351,12,1,0,1900-1959,3,5,15,76,Endeavor Air Inc.,5359,...,5,Raleigh-Durham International,35.875,-78.782,Tampa International,0.00,0.0,0.0,50.0,7.83
4012189,8,3,0,1700-1759,6,2,22,276,United Air Lines Inc.,11012,...,17,Newark Liberty International,40.696,-74.172,San Francisco International,1.69,0.0,0.0,84.0,4.25
4789024,9,5,0,0800-0859,2,1,3,76,Mesa Airlines Inc.,1378,...,2,Tulsa International,36.198,-95.890,NONE,0.00,0.0,0.0,95.0,6.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970280,3,2,0,1400-1459,6,2,58,181,American Airlines Inc.,23912,...,2,Dallas Fort Worth Regional,32.894,-97.030,Logan International,0.05,0.0,0.0,67.0,14.32
2722396,6,6,0,1500-1559,2,3,36,50,SkyWest Airlines Inc.,13872,...,16,Detroit Metro Wayne County,42.217,-83.344,Greater Binghamton/Edwin A. Link Field,0.00,0.0,0.0,77.0,5.82
1665128,4,1,0,1500-1559,3,3,46,76,SkyWest Airlines Inc.,18788,...,3,Stapleton International,39.774,-104.880,General Mitchell Field,0.07,1.0,0.0,42.0,10.29
1202368,3,2,0,2100-2159,4,6,7,143,Southwest Airlines Co.,18951,...,9,Stapleton International,39.774,-104.880,Louis Armstrong New Orleans International,0.00,0.0,0.0,46.0,10.07
1595147,4,7,0,2200-2259,1,8,69,76,"Midwest Airline, Inc.",18979,...,12,Douglas Municipal,35.219,-80.936,Theodore Francis Green State,0.00,0.0,0.0,67.0,4.92

In [28]:
muestra_df.to_csv('C:/Users/jmorano/Documents/Plantillas personalizadas de Office/Coderhouse/Data Science/Modulo 2 - Data Science Fundamentos para la Ciencia de Datos II/Proyecto - Juan Martin Morano/Data/Processed/muestra_aleatoria.csv')